### Valid request (without trailing slash)

GET http://localhost:8080/tasks

### Valid request (with trailing slash)

GET http://localhost:8080/tasks/


### Valid request (query without trailing slash)

GET http://localhost:8080/tasks?foo=bar


### Valid request (query with trailing slash)

GET http://localhost:8080/tasks/?foo=bar


### not found

GET http://localhost:8080/tasks/123

### not found

GET http://localhost:8080/tasks/foo/bar
